### ISSUE TITLE
版本号比较不正确

### ISSUE THREAD

**Issue by Allensa** [SketchK/FOUR#1]
- (BOOL)isNewVersion{
  //获取当前app的版本号
  NSString *newVersion =  @"2";//[[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"];
  //加载沙盒中的版本号记录
  NSString *currentVersion = [[NSUserDefaults standardUserDefaults] stringForKey:kCurrentVersionKey];
  //写入新的版本号
  [[NSUserDefaults standardUserDefaults] setObject:newVersion forKey:kCurrentVersionKey];
  
  return newVersion > currentVersion;
  }

怎么能拿两个字符串来直接比较大小呢?

**Comment by SwiftSIQI** [comment]
@qq73666  Hi，您好，关于这个问题，我想分为两个部分回答：
1 能不能的问题？
在NSString类型中在相同格式下应该是能进行大小比较的，例如字符串“ABC”与“ABD”进行比较的话，肯定是ABC小于ABD，所以我的想法就是，保持当前版本号样式为A.B.C的前提下，是可以进行大小比较的。
2.好不好的问题？
从严谨的角度上来说这样写确实是不太规范的。具体的代码可以参考这个答案：
http://stackoverflow.com/questions/1978456/compare-version-numbers-in-objective-c， 我会在下个版本中注意这一点的。谢谢你的提醒！
