### ISSUE TITLE
感觉4S尺寸上的适配是不是没有做？很多界面在4S上有些乱或显示不完全。

### ISSUE THREAD

**Issue by Jinxiansen** [SketchK/FOUR#12]
还有多次拷贝的 DZNEmptyDataSet 方法，为什么不二次封装一下使用呢。😁

**Comment by SwiftSIQI** [comment]
@Jinxiansen 谢谢你的建议！我会采纳的！这个确实是可以优化的一个地方

**Comment by SwiftSIQI** [comment]
@Jinxiansen 哦，对了，3.5寸屏上确实没有做适配，另外整个工程文件在屏幕适配上还存在不少问题，我会在下个版本上考虑怎么进行优化

**Comment by Jinxiansen** [comment]
@SketchK  过了一年了，都下架了，我怎么看得到下版本。
