### ISSUE TITLE
Facing problem while using updating cocoapods

### ISSUE THREAD

**Issue by uutkarshsingh** [SketchK/FOUR#13]
Hi there,
Thanks for the app. But when I try to put run 'pod install' command to install the other dependencies I get the following errors . Can you tell me what I need to do correctly to make this project run on my side.

![screen shot 2016-07-26 at 6 12 46 pm](https://cloud.githubusercontent.com/assets/3918254/17138252/0404cecc-535d-11e6-9c7f-d57c034f1fd4.png)

**Comment by SwiftSIQI** [comment]
@uutkarshsingh  Hi,I think you can download the project again and try it again, if you face the same problem, can you give me more information or image?

**Comment by uutkarshsingh** [comment]
Thanks. It has been fixed.
